### ISSUE TITLE
Sensitivity/precision tradeoff

### ISSUE THREAD

**Issue by apredeus** [fbreitwieser/krakenuniq#123]
Hi @fbreitwieser , thank you for a great tool. 

I was wondering if you have any pointers as to how one can increase sensitivity, possibly at the expense of precision? A more accurate database would probably go a long way, but I was wondering if there are other parameters that can be adjusted to achieve this.

Thank you in advance!

**Comment by salzberg** [comment]
You can build your own database and set the k-mer value to be smaller. By default it is 31. We've experimented with k-mer values down to 23, and they improve sensitivity a little bit, with a somewhat higher false positive rate, as you'd expect. I'd recommend trying k=25 and seeing what you get. It takes some time to do the experiments necessary to figure out if you get any improvement though. We've kept it at 31 because as we keep adding genomes, sensitivity just goes up naturally without losing precision.

**Comment by apredeus** [comment]
Hi Steven - thank you very much for a quick and helpful answer!
