### ISSUE TITLE
Do I need to re-build database that was built with krakenhll?

### ISSUE THREAD

**Issue by ShaiberAlon** [fbreitwieser/krakenuniq#30]
Hi,

I had an installation of krakenhll, and now upgraded to krakenuniq. Do I need to repeat the download and build of the database?

**Comment by ShaiberAlon** [comment]
I tried using krakenuniq with the old database, and got the following error:

```
Use of uninitialized value $report_file in -s at /bin/krakenuniq/krakenuniq line 179.
Use of uninitialized value $report_file in concatenation (.) or string at /bin/krakenuniq/krakenuniq line 187.
Use of uninitialized value $report_file in concatenation (.) or string at /bin/krakenuniq/krakenuniq line 187.
sh: line 1: : No such file or directory
Couldn't write report header.
```

I was using this version:
```
KrakenUniq version 0.5.5
```

And ran the following command:
```
krakenuniq \
    --preload \
    --db $PATH_TO_KRAKEN_NCBI_DB/ \
    --threads 5 \
    --fastq-input \
    --gzip-compressed \
    --paired \
    --output kraken_uniq_test \
    sample-01-R1.fastq.gz \
    sample-01-R2.fastq.gz
```

**Comment by fbreitwieser** [comment]
Hi Shaiber,
I'll look in the issue soon. krakenuniq should work on the same database. I think the issue is using --preload without --report-file. Can you try again with --report-file set? Note that you do not need --preload on every run, but only the first to cache the database.

**Comment by ShaiberAlon** [comment]
Hi @fbreitwieser, thank you for your response! You are right, I added `--report-file`, and now it's seems to be running. I guess I don't really understand what `--preload` does.

**Comment by fbreitwieser** [comment]
@ShaiberAlon , I added some more information to the `README.md`, copied below. Hope that helps! Let me know if you have more questions.

"
It can be advantegeous to preload the database prior to the first run. KrakenUniq uses mmap to map the database files into memory, which reads the file on demand. `krakenuniq --preload` reads the full database into memory, so that subsequent runs can benefit from the mapped pages. You do not need to specify preload before every run, but only after restarting the machine or when using a new database.

```
krakenuniq --db DBDIR --preload --threads 10
krakenuniq --db DBDIR --threads 10 --report-file REPORTFILE.tsv > READCLASSIFICATION.tsv
...
```

"

**Comment by ShaiberAlon** [comment]
Thank you for the clarification!
